#!/usr/bin/bash
 
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40814_R1.fq	Kidney_Mass_1_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40814_R2.fq	Kidney_Mass_1_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40815_R1.fq	Kidney_Mass_2_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40815_R2.fq	Kidney_Mass_2_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40816_R1.fq	Oviduct_Mass_3_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40816_R2.fq	Oviduct_Mass_3_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40817_R1.fq	Kidney_Mass_4_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40817_R2.fq	Kidney_Mass_4_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40818_R1.fq	Oviduct_Mass_5_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40818_R2.fq	Oviduct_Mass_5_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40819_R1.fq	Oviduct_Mass_6_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40819_R2.fq	Oviduct_Mass_6_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40820_R1.fq	Ovary_Mass_7_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40820_R2.fq	Ovary_Mass_7_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40821_R1.fq	Ovary_Mass_8_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40821_R2.fq	Ovary_Mass_8_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40822_R1.fq	Ovary_Mass_9_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40822_R2.fq	Ovary_Mass_9_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40823_R1.fq	Kidney_DMV_10_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40823_R2.fq	Kidney_DMV_10_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40824_R1.fq	Kidney_DMV_11_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40824_R2.fq	Kidney_DMV_11_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40825_R1.fq	Kidney_DMV_12_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40825_R2.fq	Kidney_DMV_12_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40826_R1.fq	Oviduct_DMV_13_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40826_R2.fq	Oviduct_DMV_13_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40827_R1.fq	Oviduct_DMV_14_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40827_R2.fq	Oviduct_DMV_14_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40828_R1.fq	Oviduct_DMV_15_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40828_R2.fq	Oviduct_DMV_15_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40829_R1.fq	Ovary_DMV_16_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40829_R2.fq	Ovary_DMV_16_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40830_R1.fq	Ovary_DMV_17_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40830_R2.fq	Ovary_DMV_17_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40831_R1.fq	Ovary_DMV_18_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40831_R2.fq	Ovary_DMV_18_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40832_R1.fq	Kidney_ConDMV_19_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40832_R2.fq	Kidney_ConDMV_19_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40833_R1.fq	Kidney_ConDMV_20_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40833_R2.fq	Kidney_ConDMV_20_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40834_R1.fq	Kidney_ConDMV_21_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40834_R2.fq	Kidney_ConDMV_21_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40835_R1.fq	Oviduct_ConDMV_22_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40835_R2.fq	Oviduct_ConDMV_22_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40836_R1.fq	Oviduct_ConDMV_23_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40836_R2.fq	Oviduct_ConDMV_23_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40837_R1.fq	Oviduct_ConDMV_24_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40837_R2.fq	Oviduct_ConDMV_24_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40838_R1.fq	Ovary_ConDMV_25_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40838_R2.fq	Ovary_ConDMV_25_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40839_R1.fq	Ovary_ConDMV_26_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40839_R2.fq	Ovary_ConDMV_26_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40840_R1.fq	Ovary_ConDMV_27_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40840_R2.fq	Ovary_ConDMV_27_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40841_R1.fq	Kidney_DMV_28_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40841_R2.fq	Kidney_DMV_28_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40842_R1.fq	Kidney_DMV_29_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40842_R2.fq	Kidney_DMV_29_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40843_R1.fq	Kidney_DMV_30_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40843_R2.fq	Kidney_DMV_30_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40844_R1.fq	Oviduct_DMV_31_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40844_R2.fq	Oviduct_DMV_31_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40845_R1.fq	Oviduct_DMV_32_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40845_R2.fq	Oviduct_DMV_32_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40846_R1.fq	Oviduct_DMV_33_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40846_R2.fq	Oviduct_DMV_33_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40847_R1.fq	Ovary_DMV_34_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40847_R2.fq	Ovary_DMV_34_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40848_R1.fq	Ovary_DMV_35_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40848_R2.fq	Ovary_DMV_35_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40849_R1.fq	Ovary_DMV_36_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40849_R2.fq	Ovary_DMV_36_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40850_R1.fq	Kidney_Mass_37_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40850_R2.fq	Kidney_Mass_37_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40851_R1.fq	Kidney_Mass_38_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40851_R2.fq	Kidney_Mass_38_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40852_R1.fq	Kidney_Mass_39_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40852_R2.fq	Kidney_Mass_39_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40853_R1.fq	Oviduct_Mass_40_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40853_R2.fq	Oviduct_Mass_40_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40854_R1.fq	Oviduct_Mass_41_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40854_R2.fq	Oviduct_Mass_41_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40855_R1.fq	Oviduct_Mass_42_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40855_R2.fq	Oviduct_Mass_42_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40856_R1.fq	Ovary_Mass_43_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40856_R2.fq	Ovary_Mass_43_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40857_R1.fq	Ovary_Mass_44_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40857_R2.fq	Ovary_Mass_44_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40858_R1.fq	Ovary_Mass_45_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40858_R2.fq	Ovary_Mass_45_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40859_R1.fq	Kidney_ConDMV_46_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40859_R2.fq	Kidney_ConDMV_46_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40860_R1.fq	Kidney_ConDMV_47_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40860_R2.fq	Kidney_ConDMV_47_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40861_R1.fq	Kidney_ConDMV_48_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40861_R2.fq	Kidney_ConDMV_48_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40862_R1.fq	Oviduct_ConDMV_49_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40862_R2.fq	Oviduct_ConDMV_49_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40863_R1.fq	Oviduct_ConDMV_50_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40863_R2.fq	Oviduct_ConDMV_50_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40864_R1.fq	Oviduct_ConDMV_51_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40864_R2.fq	Oviduct_ConDMV_51_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40865_R1.fq	Ovary_ConDMV_52_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40865_R2.fq	Ovary_ConDMV_52_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40866_R1.fq	Ovary_ConDMV_53_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40866_R2.fq	Ovary_ConDMV_53_R2.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40867_R1.fq	Ovary_ConDMV_54_R1.fq
cp /work/careem_lab/Avian_smallRNAseq/mRNAs/Avian_mRNA_Seq/Li40867_R2.fq	Ovary_ConDMV_54_R2.fq
